# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [1]:
import numpy as np 

#### Q2 : Afficher la version de numpy et la configuration 

#### Q3 : Créer un vecteur nul de taille 10

In [8]:
np.array([0,0,0,0,0,0,0,0,0,0])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [9]:
a = np.array([0,0,0,0,0,0,0,0,0,0])
a[4] = 1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [12]:
b = np.arange(start=10,stop=51); b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [17]:
b[-1] = b[0]
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 10])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [19]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q8 : Créer une matrice identié 3x3 

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [22]:
rd = np.random
rd.rand(3,3,3)

array([[[0.4995963 , 0.62708959, 0.86363921],
        [0.02556175, 0.3360675 , 0.63854115],
        [0.96498434, 0.09928703, 0.49374492]],

       [[0.25679649, 0.48610149, 0.85131495],
        [0.69899971, 0.23295994, 0.6696193 ],
        [0.29036205, 0.46397513, 0.76431702]],

       [[0.92036137, 0.01229637, 0.97340987],
        [0.73801477, 0.3308174 , 0.45941176],
        [0.52612641, 0.85931858, 0.7206823 ]]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [25]:
d = rd.rand(3,3,3); d
d.min()
d.max()

0.9778998395953351

#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [26]:
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [68]:
e = rd.rand(5); e
e.sum()

2.2475919953149273

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [29]:
f = rd.rand(5); f
f.mean()

0.5659373694082147

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

In [34]:
l = [x for x in range(11)]
m = lambda x : len(x)
m(l)

11

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [36]:
rd.ranf(10)

array([0.45533963, 0.37366796, 0.10774142, 0.69751375, 0.64518826,
       0.05433572, 0.18930305, 0.80996348, 0.6171803 , 0.07820794])

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [46]:
A = np.arange(5); A
B = np.arange(5); B
np.array_equal(A,B)

True

#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [58]:
g = np.arange(10, dtype='float32'); 
g = g.astype('int32'); g

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

In [75]:
m = rd.randint(5, size=(5, 5))
mean = m.mean()
ecartType = m.std()
np.divide(np.subtract(m, mean), ecartType) 


array([[ 1.34781744,  1.34781744, -0.0860309 , -0.80295507,  1.34781744],
       [-0.80295507, -1.51987924,  0.63089327, -0.0860309 ,  0.63089327],
       [ 0.63089327, -0.80295507, -0.0860309 ,  0.63089327, -1.51987924],
       [-1.51987924,  1.34781744, -1.51987924,  0.63089327,  1.34781744],
       [ 0.63089327,  0.63089327, -0.80295507, -0.80295507, -0.80295507]])

#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

In [78]:
n = rd.randint(5, size=(2, 2)); n
n.transpose()

array([[3, 1],
       [2, 4]])

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

In [90]:
dim = 10
matrice = rd.randint(5, size=(dim, dim))
rand = rd.randint(0, 10, 2)
matrice[rand[0]][rand[1]] = 12
matrice

array([[ 0,  2,  0,  3,  0,  1,  2,  0,  4,  4],
       [ 2,  1,  1,  1,  0,  1,  0,  1,  2,  4],
       [ 4,  2,  4,  1,  1,  1,  1,  0,  0,  4],
       [ 1,  0,  0,  2,  3,  2,  2,  2,  0,  4],
       [ 4,  0,  4,  1,  2,  0,  0,  0,  3,  0],
       [ 0,  1,  1,  3,  4,  4,  3,  0,  2,  4],
       [ 1,  4,  0, 12,  0,  4,  3,  2,  4,  0],
       [ 1,  4,  1,  1,  3,  4,  2,  1,  0,  0],
       [ 1,  3,  4,  2,  4,  0,  1,  1,  3,  0],
       [ 0,  2,  1,  3,  1,  3,  2,  0,  1,  1]])

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)

In [95]:
matA = rd.randint(10, size=(5, 3,5));
matB = rd.randint(10, size=(5, 5));
np.matmul(matA, matB)

array([[[ 96,  86, 124, 114,  95],
        [129, 136, 195, 178, 128],
        [121, 127, 184, 170, 122]],

       [[ 74, 103, 173, 150,  92],
        [ 50,  50,  55,  65,  45],
        [ 71,  93, 165, 148,  97]],

       [[ 75,  85, 145, 116,  83],
        [127, 112, 176, 127, 112],
        [100,  73, 122, 112, 110]],

       [[ 75,  87, 156, 109,  79],
        [173, 157, 224, 190, 156],
        [102,  94, 135,  96,  81]],

       [[105,  84, 109,  86,  83],
        [144, 123, 150, 135, 114],
        [107,  96, 147, 111,  97]]])