In [1]:
import numpy as np
rd = np.random


# Quelques fonctions utiles

On a créé un tableau 2D `rdm_mat` contenant des valeurs aléatoires. 

In [4]:
import numpy as np
rd = np.random
rdm_mat = rd.randn(4,2)
print(rdm_mat)

[[ 0.64048218  1.06610988]
 [-0.58806208  0.96197009]
 [-1.48361321  0.37949168]
 [-0.69447119  0.42745743]]


Donner le type de la variable rdm_mat

In [7]:
rdm_mat.dtype

dtype('float64')

Donner la somme des éléments de ce tableau 2D

In [11]:
rdm_mat.cumsum()[-1]

0.7093647899088208

Faire en sorte de récupérer la valeur maximale sur chaque ligne (sans boucles) avec la fonction np.max

In [14]:
np.amax(rdm_mat, axis=1)

array([1.06610988, 0.96197009, 0.37949168, 0.42745743])

Faire de même pour récupérer la valeur maximum pour chaque colonne (sans boucles)

In [15]:
np.amax(rdm_mat, axis=0)

array([0.64048218, 1.06610988])

Faire la même chose (max des lignes) en définissant un tableau avec une boucle for et la fonction max de numpy

On crée un vecteur aléatoire de taille 100 `rdm_vect`

In [17]:
rdm_vect = np.random.randn(100)
rdm_vect.shape
rdm_vect

array([-0.86509732, -0.40815062,  1.37091106,  1.32288762,  1.28577998,
       -0.48953307, -0.01631169,  0.69674547, -1.471156  ,  1.4756177 ,
        1.13845355, -2.38837082,  1.25333125, -0.4142232 ,  1.43141541,
        0.720728  ,  0.31207102,  1.41803295, -1.46213663, -1.34744451,
        1.388437  , -0.43240803,  0.0576342 , -0.08743391, -1.53631832,
       -0.91800957,  0.00468984,  1.31593406,  1.15744456, -0.4862837 ,
        1.07372012,  0.29538641,  0.09936326, -0.90108841, -0.72745098,
        0.03004055, -0.8009635 ,  1.75701218,  0.30757734,  1.79404605,
       -0.04952201,  1.03701496,  0.91232938,  0.25666107,  1.43302125,
       -1.74329652,  0.83019289, -0.04321409,  1.33682906,  1.09481752,
       -0.46590208,  2.21247883,  1.68725646, -0.52376996,  0.78335708,
        0.65966664, -0.77708486, -0.33537441, -1.64791121, -0.64838321,
       -0.81682926,  0.86710728, -0.11723965, -0.35284887, -0.88182415,
       -0.3839918 ,  0.92901623,  1.62842797,  0.78394344, -0.37

Récupérer la position de la valeur maximale du vecteur avec la méthode np.argmax

In [19]:
np.argmax(rdm_vect)

92

Afficher cette valeur 

In [20]:
rdm_vect[92]

2.495552503710119

Convertir le vecteur en un tableau 10, 10

In [25]:
r = rdm_vect.reshape(10, 10); r

array([[-0.86509732, -0.40815062,  1.37091106,  1.32288762,  1.28577998,
        -0.48953307, -0.01631169,  0.69674547, -1.471156  ,  1.4756177 ],
       [ 1.13845355, -2.38837082,  1.25333125, -0.4142232 ,  1.43141541,
         0.720728  ,  0.31207102,  1.41803295, -1.46213663, -1.34744451],
       [ 1.388437  , -0.43240803,  0.0576342 , -0.08743391, -1.53631832,
        -0.91800957,  0.00468984,  1.31593406,  1.15744456, -0.4862837 ],
       [ 1.07372012,  0.29538641,  0.09936326, -0.90108841, -0.72745098,
         0.03004055, -0.8009635 ,  1.75701218,  0.30757734,  1.79404605],
       [-0.04952201,  1.03701496,  0.91232938,  0.25666107,  1.43302125,
        -1.74329652,  0.83019289, -0.04321409,  1.33682906,  1.09481752],
       [-0.46590208,  2.21247883,  1.68725646, -0.52376996,  0.78335708,
         0.65966664, -0.77708486, -0.33537441, -1.64791121, -0.64838321],
       [-0.81682926,  0.86710728, -0.11723965, -0.35284887, -0.88182415,
        -0.3839918 ,  0.92901623,  1.62842797

Calculer la moyenne de chaque ligne de ce tableau (sans boucles)

In [27]:
r.mean(axis=0)

array([ 8.20137714e-02,  7.56479409e-04,  8.73059030e-01,  7.17491379e-02,
        2.46763779e-01, -1.82279965e-01, -1.40944458e-02,  4.50634362e-01,
       -1.87712377e-01,  2.02439847e-01])

Faire un tableau qui contient la moyenne de chaque colonne du tableau 

Calculer la somme de chaque colonne (sans boucles)

In [28]:
r.mean(axis=1)

array([ 0.29016932,  0.0661857 ,  0.04636861,  0.2927643 ,  0.50648335,
        0.09443333,  0.12780528, -0.20880957, -0.06796021,  0.39588951])

Calculer la somme pour chaque ligne (sans boucles)

In [29]:
r.sum(axis=0)

array([ 8.20137714e-01,  7.56479409e-03,  8.73059030e+00,  7.17491379e-01,
        2.46763779e+00, -1.82279965e+00, -1.40944458e-01,  4.50634362e+00,
       -1.87712377e+00,  2.02439847e+00])